--[[ 
.mob files are Minecraft .obj files
they store a very simple 3d array of values that represents a structure
mobc converts tcode generated by tprint into .mob files, and vice versa

format of .mob objects:
{
    width=num,
    height=num,
    depth=num,
    model={
        { --layer
            { 1, 1, 1 }, --row
            { 1, 0, 1 },
            { 1, 0, 1 }
        },
        {
            { 1, 1, 1 },
            { 1, 0, 1 },
            { 1, 0, 1 }
        },
        {
            { 1, 1, 1 },
            { 1, 1, 1 },
            { 1, 1, 1 }
        },
    },
    materials={
        {name="block-name", amount=num}
    }
}
--]]


local function tcodeToMob(tcodeObj)
    local mob = {
        width=tcodeObj.width,
        height=tcodeObj.height,
        depth=tcodeObj.depth,
        model={},
        materials={}
    }
    for i=1,height do
        mob.model[i] = {}
        for j=1,depth do
            mob.model[i][j] = {}
        end
    end
    local pw = 1
    local ph = 1
    local pd = tcodeObj.depth
    local direction = -1
    for i in ipairs(tcodeObj.data) do
        mob.model[ph][pd][pw] = tcodeObj.data[i]
        if tcodeObj.instructions[i] == "forward" then
            pd = pd + direction
        elseif tcodeObj.instructions[i] == "right" then
            pw = pw + (-direction)
            direction = -direction
        elseif tcodeObj.instructions[i] == "left" then
            pw = pw + direction
            direction = -direction
        elseif tcodeObj.instructions[i] == "up" then
            ph = ph + 1
            direction = -direction
        end
    end
end