--[[ 
.mob files are Minecraft .obj files
they store a very simple 3d array of values that represents a structure
mobc converts tcode generated by tprint into .mob files, and vice versa

format of .mob objects:
{
    width=num,
    height=num,
    depth=num,
    model={
        { --layer
            { 1, 1, 1 }, --row
            { 1, 0, 1 },
            { 1, 0, 1 }
        },
        {
            { 1, 1, 1 },
            { 1, 0, 1 },
            { 1, 0, 1 }
        },
        {
            { 1, 1, 1 },
            { 1, 1, 1 },
            { 1, 1, 1 }
        },
    },
    materials={
        {name="block-name", amount}
    }
}
--]]


local function tcodeToMob(tcodeObj)
    local mob = {
        width=tcodeObj.width,
        height=tcodeObj.height,
        depth=tcodeObj.depth,
    }
end